# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

jobs:
  # build ジョブ: CircleCI 上で Docker コンテナを作成してテストする
  build:
    docker:
      - image: node:20
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
  # deploy ジョブ: EC2 に SSH 接続して、デプロイを実行する
  deploy:
    machine:
      image: ubuntu-2004:202008-01
      resource_class: medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build React App
          command: npm run build
      # CircleCI に登録した秘密鍵を呼び出す
      - add_ssh_keys
      - run:
          name: Deploy to EC2
          command: scp -r ./build ${USER_NAME}@${HOST_NAME}:/var/www/html
workflows:
  version: 2
  # build_and_deploy ジョブ: 一番最初に呼ばれるジョブ
  build_and_deploy:
    # build ジョブと deploy ジョブを登録する
    jobs:
      - build
      - deploy:
          requires:
            # 依存性あるから deploy ジョブより先に build ジョブを実行してね、という命令
            - build
          # master ブランチに push された場合のみ deploy ジョブを実行する
          filters:
            branches:
              only: main
